title:            ClearTsai Fighting @strongwillow
url:              http://www.cleartsai.com
permalink:        pretty
pygments:         true
markdown:         rdiscount
rdiscount:
  extensions:     [smart]
google_analytics: 
timezone:         GMT+8
paginate: 5
links: 
  - name:         About
    url:          /about