title:            蔡蔡不菜 - @strongwillow
url:              http://www.cleartsai.com
permalink:        pretty
pygments:         true
markdown:         rdiscount
rdiscount:
  extensions:     [smart]
google_analytics: 
timezone:         Europe/London
paginate: 5
links: 
  - name:         About
    url:          /about