title:            蔡蔡不菜 
description:      A jekyll theme. Because I scribble.
url:              http://www.cleartsai.com 
signoff:          Strongwillow 
paginate: 5

links:
  - name:         About
    url:          /about
  - name:         GitHub
    url:          http://github.com/strongwillow
    external:     true
  - name:         Instagram
    url:          http://instagram.com/strongwillow
    external:     true
  - name:         Pinterest
    url:          http://pinterest.com/strongwillow/
    external:     true
  - name:         Delicious
    url:          https://delicious.com/strongwillow
    external:     true

pygments:      	  true 
permalink:        pretty
markdown:         rdiscount
rdiscount:
  extensions:     [smart]
